site_name: DOCUMENTATION
nav:
  - MOBILE MONETIZATION PRO:
    - Get Started: index.md
    - Admob Ads Part-1: AdmobAdsSetup.md
    - Admob Ads Mediation Part-2: AdmobAdsSetup_Part2_Mediation.md
    - Admob Ads Callback Part-3: AdmobAdsSetup_Part3.md
    - LevelPlay Ads Part-1: LevelPlayAdsSetup.md
    - LevelPlay Ads Part-2: LevelPlayAdsCallbacks.md
    - Applovin Ads Part-1: ApplovinSetup.md
    - Applovin Ads Part-2: ApplovinMediationSetup.md
    - LiftOff Ads: VungleAds.md
    - Setup GDPR: SetupGDPR.md
    - Setup App Tracking Transparency: SetupATT.md
    - In App Purchase Setup Part-1: SetupIAPOnStores.md
    - In App Purchase Setup Part-2: SetupIAPInUnity.md
    - Local Mobile Notifications: LocalNotifications.md
    - Remote Notifications: RemoteNotifications.md
    - In App Update: InAppUpdate.md
    - Rate Game Popup: RateGame.md
    - Internet Connectivity Checks: NoInternetChecks.md
    - Cross-Promotion: CrossPromotion.md
    - Firebase Analytics: FirebaseAnalytics.md
    - Solutions:
       - Fix Win32 Exception Error: FixWin32Exception.md
       - Fix Android Specific Scripts: AndroidSpecificScripts.md
  - SUPPORT: SupportMobileMonetizationPro.md
docs_dir: docs
use_directory_urls: false
theme:
  name: material
  logo: Images/Logo.png
  favicon: Images/Logo.png
  custom_dir: docs/overrides
  nav_style: default
  features:
    - navigation.tabs
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.copy.code
    - prev_next_buttons
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: white
      accent: white
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent:  black
plugins:
  - search
extra_css:
  - overrides/extra.css
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/BeGy5hhyNj
    - icon: fontawesome/solid/envelope
      link: https://mail.google.com/


